export {default as conformToMask} from './conformToMask'
export {default as adjustCaretPosition} from './adjustCaretPosition'
export {default as createTextMaskInputElement} from './createTextMaskInputElement'
export {default as convertMaskToPlaceholder} from './utilities'
export {placeholderChar} from './constants'
